import type { ModuleConfig, RelationConfig, ReportConfig } from "./moduleTypes";

const activeFilter = {
  name: "isActive",
  label: "Active",
  type: "select" as const,
  options: [
    { label: "All", value: "" },
    { label: "Active", value: "true" },
    { label: "Inactive", value: "false" },
  ],
};

const statusFilter = (statuses: string[]) => ({
  name: "status",
  label: "Status",
  type: "select" as const,
  options: [
    { label: "All", value: "" },
    ...statuses.map((status) => ({ label: status.replace(/_/g, " "), value: status })),
  ],
});

export const moduleConfigs = {
  items: {
    title: "Items",
    subtitle: "Manage SKUs, units, tracking rules, thresholds, and stock references.",
    routeKey: "items.list",
    createRouteKey: "items.create",
    detailRouteKey: "items.getById",
    updateRouteKey: "items.update",
    deleteRouteKey: "items.delete",
    newPath: "/inventory/items/new",
    detailPath: "/inventory/items/:id",
    searchPlaceholder: "Search item name, SKU, barcode",
    filters: [activeFilter],
    columns: [
      { key: "sku", label: "SKU" },
      { key: "name", label: "Item" },
      { key: "unit", label: "Unit" },
      { key: "reorderPoint", label: "Reorder", align: "right" },
      { key: "isActive", label: "Status", status: true },
    ],
    fields: [
      { name: "name", label: "Item name", required: true },
      { name: "sku", label: "SKU", required: true },
      {
        name: "unit",
        label: "Unit",
        type: "select",
        required: true,
        defaultValue: "pcs",
        options: [
          { label: "Pieces", value: "pcs" },
          { label: "Kilogram", value: "kg" },
          { label: "Litre", value: "ltr" },
          { label: "Metre", value: "mtr" },
          { label: "Box", value: "box" },
          { label: "Dozen", value: "dozen" },
          { label: "Set", value: "set" },
        ],
      },
      { name: "description", label: "Description", type: "textarea" },
      {
        name: "categoryId",
        label: "Category",
        type: "select",
        required: true,
        placeholder: "Select active category",
        dynamicOptions: {
          routeKey: "categories.list",
          labelKey: "name",
          valueKey: "id",
          query: { isActive: true },
        },
        helper: "Only active categories from your current organization can be used.",
      },
      { name: "barcode", label: "Barcode" },
      { name: "reorderPoint", label: "Reorder point", type: "number" },
      { name: "reorderQuantity", label: "Reorder quantity", type: "number" },
      { name: "trackBatches", label: "Track batches", type: "checkbox" },
      { name: "trackExpiry", label: "Track expiry", type: "checkbox" },
      { name: "isAsset", label: "Asset item", type: "checkbox" },
    ],
  },
  categories: {
    title: "Categories",
    subtitle: "Organize inventory with nested item categories.",
    routeKey: "categories.list",
    createRouteKey: "categories.create",
    updateRouteKey: "categories.update",
    deleteRouteKey: "categories.delete",
    newPath: "/inventory/categories/new",
    columns: [
      { key: "name", label: "Category" },
      { key: "code", label: "Code" },
      { key: "parentCategoryId.name", label: "Parent" },
      { key: "isActive", label: "Status", status: true },
    ],
    fields: [
      { name: "name", label: "Category name", required: true },
      { name: "code", label: "Code" },
      { name: "parentCategoryId", label: "Parent category ID" },
      { name: "description", label: "Description", type: "textarea" },
    ],
  },
  stockLevels: {
    title: "Stock Levels",
    subtitle: "Review item balances across warehouses and zones.",
    routeKey: "inventory.balances",
    newPath: "/inventory/stock-in",
    newLabel: "Stock In",
    columns: [
      { key: "itemId.name", label: "Item" },
      { key: "warehouseId.name", label: "Warehouse" },
      { key: "zoneId.name", label: "Zone" },
      { key: "quantity", label: "Qty", align: "right" },
      { key: "reservedQuantity", label: "Reserved", align: "right" },
      { key: "availableQuantity", label: "Available", align: "right" },
    ],
  },
  stockIn: {
    title: "Stock In",
    subtitle: "Add opening stock or received stock into a warehouse.",
    createRouteKey: "inventory.stockIn",
    columns: [],
    fields: [
      {
        name: "itemId",
        label: "Item",
        type: "select",
        required: true,
        placeholder: "Select item",
        dynamicOptions: {
          routeKey: "items.list",
          labelKey: "name",
          valueKey: "id",
          query: { isActive: true },
        },
        helper: "Use the item you created, for example Mobile.",
      },
      {
        name: "warehouseId",
        label: "Warehouse",
        type: "select",
        required: true,
        placeholder: "Select warehouse",
        dynamicOptions: {
          routeKey: "warehouses.list",
          labelKey: "name",
          valueKey: "id",
          query: { isActive: true },
        },
        helper: "Stock is stored against one warehouse.",
      },
      { name: "quantity", label: "Quantity", type: "number", required: true },
      {
        name: "unitCost",
        label: "Unit cost",
        type: "number",
        helper: "Optional. Used for inventory value.",
      },
      {
        name: "batchNumber",
        label: "Batch number",
        helper: "Required when the item has Track batches enabled.",
      },
      {
        name: "expiryDate",
        label: "Expiry date",
        type: "date",
        helper: "Required when the item has Track expiry enabled.",
      },
      { name: "manufacturingDate", label: "Manufacturing date", type: "date" },
      {
        name: "serialNumbers",
        label: "Serial numbers JSON",
        type: "json",
        helper: "[\"MOB-SN-001\", \"MOB-SN-002\"] - optional. Count must match quantity if used.",
      },
      { name: "notes", label: "Notes", type: "textarea" },
    ],
  },
  movements: {
    title: "Stock Movements",
    subtitle: "Audit inbound, outbound, transfer, and reconciliation movements.",
    routeKey: "stock.movements",
    filters: [statusFilter(["IN", "OUT", "TRANSFER", "ADJUSTMENT", "RECONCILIATION"])],
    columns: [
      { key: "type", label: "Type", status: true },
      { key: "itemId.name", label: "Item" },
      { key: "warehouseId.name", label: "Warehouse" },
      { key: "quantity", label: "Qty", align: "right" },
      { key: "occurredAt", label: "Occurred" },
    ],
  },
  lowStock: {
    title: "Low Stock",
    subtitle: "Items and balances below configured threshold.",
    routeKey: "items.lowStock",
    columns: [
      { key: "itemId.name", label: "Item" },
      { key: "warehouseId.name", label: "Warehouse" },
      { key: "availableQuantity", label: "Available", align: "right" },
      { key: "reorderPoint", label: "Threshold", align: "right" },
    ],
  },
  expiring: {
    title: "Expiring Stock",
    subtitle: "Batch-tracked stock approaching expiry.",
    routeKey: "items.expiring",
    columns: [
      { key: "itemId.name", label: "Item" },
      { key: "batchNumber", label: "Batch" },
      { key: "warehouseId.name", label: "Warehouse" },
      { key: "expiryDate", label: "Expiry" },
      { key: "quantity", label: "Qty", align: "right" },
    ],
  },
  deadStock: {
    title: "Dead Stock",
    subtitle: "Items with no movement in the selected window.",
    routeKey: "items.deadStock",
    columns: [
      { key: "sku", label: "SKU" },
      { key: "name", label: "Item" },
      { key: "lastMovementAt", label: "Last movement" },
      { key: "availableQuantity", label: "Available", align: "right" },
    ],
  },
  warehouses: {
    title: "Warehouses",
    subtitle: "Manage warehouse master data, managers, and operational status.",
    routeKey: "warehouses.list",
    createRouteKey: "warehouses.create",
    detailRouteKey: "warehouses.getById",
    updateRouteKey: "warehouses.update",
    deleteRouteKey: "warehouses.delete",
    newPath: "/warehouses/new",
    detailPath: "/warehouses/:id",
    filters: [activeFilter],
    columns: [
      { key: "code", label: "Code" },
      { key: "name", label: "Warehouse" },
      { key: "type", label: "Type" },
      { key: "managerId.name", label: "Manager" },
      { key: "isActive", label: "Status", status: true },
    ],
    fields: [
      { name: "name", label: "Warehouse name", required: true },
      { name: "code", label: "Code", required: true },
      {
        name: "type",
        label: "Type",
        type: "select",
        defaultValue: "main",
        options: [
          { label: "Main", value: "main" },
          { label: "Secondary", value: "secondary" },
          { label: "Transit", value: "transit" },
        ],
      },
      {
        name: "address",
        label: "Address JSON",
        type: "json",
        helper: "{\"city\":\"Mumbai\",\"state\":\"MH\",\"pincode\":\"400001\"}",
      },
      { name: "contactPhone", label: "Contact phone" },
      { name: "managerId", label: "Manager user ID" },
    ],
  },
  requests: {
    title: "Requests",
    subtitle: "Track department stock requests from draft to fulfillment.",
    routeKey: "requests.list",
    createRouteKey: "requests.create",
    detailRouteKey: "requests.getById",
    updateRouteKey: "requests.update",
    newPath: "/requests/new",
    detailPath: "/requests/:id",
    filters: [statusFilter(["DRAFT", "PENDING", "DEPT_APPROVED", "STORE_APPROVED", "FULFILLED", "REJECTED", "CANCELLED"])],
    columns: [
      { key: "requestNumber", label: "Request" },
      { key: "departmentId.name", label: "Department" },
      { key: "priority", label: "Priority", status: true },
      { key: "status", label: "Status", status: true },
      { key: "createdAt", label: "Created" },
    ],
    fields: [
      { name: "departmentId", label: "Department ID", required: true },
      { name: "warehouseId", label: "Warehouse ID" },
      { name: "priority", label: "Priority", type: "select", options: [
        { label: "Low", value: "LOW" },
        { label: "Medium", value: "MEDIUM" },
        { label: "High", value: "HIGH" },
        { label: "Urgent", value: "URGENT" },
      ] },
      { name: "requiredBy", label: "Required by", type: "date" },
      { name: "purpose", label: "Purpose", type: "textarea" },
      { name: "items", label: "Items JSON", type: "json", helper: "[{\"itemId\":\"...\",\"requestedQuantity\":1}]" },
    ],
    actions: [
      { label: "Submit", routeKey: "requests.submit" },
      { label: "Approve", routeKey: "requests.approve", tone: "primary" },
      { label: "Reject", routeKey: "requests.reject", tone: "danger", payload: { reason: "Rejected from frontend" } },
      { label: "Fulfill", routeKey: "requests.fulfill", tone: "primary" },
      { label: "Cancel", routeKey: "requests.cancel", tone: "danger", payload: { reason: "Cancelled from frontend" } },
    ],
  },
  pendingRequests: {
    title: "Pending Approvals",
    subtitle: "Requests waiting for the current role to act.",
    routeKey: "requests.pending",
    detailPath: "/requests/:id",
    columns: [
      { key: "requestNumber", label: "Request" },
      { key: "departmentId.name", label: "Department" },
      { key: "priority", label: "Priority", status: true },
      { key: "status", label: "Status", status: true },
      { key: "createdAt", label: "Created" },
    ],
  },
  departments: {
    title: "Departments",
    subtitle: "Manage departments, budget ownership, and request scope.",
    routeKey: "departments.list",
    createRouteKey: "departments.create",
    detailRouteKey: "departments.getById",
    updateRouteKey: "departments.update",
    deleteRouteKey: "departments.delete",
    newPath: "/departments/new",
    detailPath: "/departments/:id",
    filters: [activeFilter],
    columns: [
      { key: "code", label: "Code" },
      { key: "name", label: "Department" },
      { key: "headId.name", label: "Head" },
      { key: "budgetAllocated", label: "Budget", align: "right" },
      { key: "isActive", label: "Status", status: true },
    ],
    fields: [
      { name: "name", label: "Department name", required: true },
      { name: "code", label: "Code", required: true },
      { name: "headId", label: "Head user ID" },
      { name: "budgetAllocated", label: "Budget allocated", type: "number" },
      { name: "description", label: "Description", type: "textarea" },
    ],
  },
  vendors: {
    title: "Vendors",
    subtitle: "Maintain supplier contacts, terms, ratings, and procurement history.",
    routeKey: "vendors.list",
    createRouteKey: "vendors.create",
    detailRouteKey: "vendors.getById",
    updateRouteKey: "vendors.update",
    deleteRouteKey: "vendors.delete",
    newPath: "/vendors/new",
    detailPath: "/vendors/:id",
    filters: [activeFilter],
    columns: [
      { key: "code", label: "Code" },
      { key: "name", label: "Vendor" },
      { key: "email", label: "Email" },
      { key: "phone", label: "Phone" },
      { key: "rating", label: "Rating", align: "right" },
    ],
    fields: [
      { name: "name", label: "Vendor name", required: true },
      { name: "code", label: "Code" },
      { name: "email", label: "Email", type: "email" },
      { name: "phone", label: "Phone" },
      { name: "paymentTerms", label: "Payment terms" },
      { name: "address", label: "Address JSON", type: "json", helper: "{\"city\":\"Mumbai\",\"country\":\"India\"}" },
    ],
  },
  purchaseOrders: {
    title: "Purchase Orders",
    subtitle: "Create, approve, send, receive, and cancel supplier orders.",
    routeKey: "purchaseOrders.list",
    createRouteKey: "purchaseOrders.create",
    detailRouteKey: "purchaseOrders.getById",
    updateRouteKey: "purchaseOrders.update",
    newPath: "/purchase-orders/new",
    detailPath: "/purchase-orders/:id",
    filters: [statusFilter(["DRAFT", "PENDING", "APPROVED", "SENT", "PARTIALLY_RECEIVED", "RECEIVED", "CANCELLED", "REJECTED"])],
    columns: [
      { key: "poNumber", label: "PO" },
      { key: "vendorId.name", label: "Vendor" },
      { key: "warehouseId.name", label: "Warehouse" },
      { key: "status", label: "Status", status: true },
      { key: "totalAmount", label: "Total", align: "right" },
    ],
    fields: [
      { name: "vendorId", label: "Vendor ID", required: true },
      { name: "warehouseId", label: "Warehouse ID", required: true },
      { name: "expectedDeliveryDate", label: "Expected delivery", type: "date" },
      { name: "items", label: "Items JSON", type: "json", helper: "[{\"itemId\":\"...\",\"quantity\":1,\"unitCost\":10}]" },
      { name: "notes", label: "Notes", type: "textarea" },
    ],
    actions: [
      { label: "Submit", routeKey: "purchaseOrders.submit" },
      { label: "Approve", routeKey: "purchaseOrders.approve", tone: "primary" },
      { label: "Reject", routeKey: "purchaseOrders.reject", tone: "danger", payload: { reason: "Rejected from frontend" } },
      { label: "Send", routeKey: "purchaseOrders.send" },
      { label: "Cancel", routeKey: "purchaseOrders.cancel", tone: "danger", payload: { reason: "Cancelled from frontend" } },
    ],
  },
  grn: {
    title: "Goods Received Notes",
    subtitle: "Review received purchase-order stock and inspection details.",
    routeKey: "grn.list",
    detailRouteKey: "grn.getById",
    detailPath: "/grn/:id",
    columns: [
      { key: "grnNumber", label: "GRN" },
      { key: "purchaseOrderId.poNumber", label: "PO" },
      { key: "vendorId.name", label: "Vendor" },
      { key: "warehouseId.name", label: "Warehouse" },
      { key: "receivedAt", label: "Received" },
    ],
  },
  payments: {
    title: "Payments",
    subtitle: "Record and review vendor payment transactions.",
    routeKey: "payments.list",
    createRouteKey: "payments.create",
    newPath: "/payments/new",
    columns: [
      { key: "vendorId.name", label: "Vendor" },
      { key: "purchaseOrderId.poNumber", label: "PO" },
      { key: "amount", label: "Amount", align: "right" },
      { key: "mode", label: "Mode", status: true },
      { key: "paidAt", label: "Paid at" },
    ],
    fields: [
      { name: "vendorId", label: "Vendor ID", required: true },
      { name: "purchaseOrderId", label: "Purchase order ID" },
      { name: "amount", label: "Amount", type: "number", required: true },
      { name: "mode", label: "Mode", required: true },
      { name: "reference", label: "Reference" },
      { name: "paidAt", label: "Paid at", type: "date" },
    ],
  },
  assets: {
    title: "Assets",
    subtitle: "Manage tagged assets, assignments, maintenance, and disposal.",
    routeKey: "assets.list",
    createRouteKey: "assets.create",
    detailRouteKey: "assets.getById",
    updateRouteKey: "assets.update",
    newPath: "/assets/new",
    detailPath: "/assets/:id",
    filters: [statusFilter(["AVAILABLE", "ASSIGNED", "MAINTENANCE", "DISPOSED", "LOST", "DAMAGED"])],
    columns: [
      { key: "assetTag", label: "Tag" },
      { key: "itemId.name", label: "Item" },
      { key: "warehouseId.name", label: "Warehouse" },
      { key: "status", label: "Status", status: true },
      { key: "currentValue", label: "Value", align: "right" },
    ],
    fields: [
      { name: "itemId", label: "Item ID", required: true },
      { name: "warehouseId", label: "Warehouse ID", required: true },
      { name: "zoneId", label: "Zone ID" },
      { name: "purchaseValue", label: "Purchase value", type: "number" },
      { name: "purchaseDate", label: "Purchase date", type: "date" },
      { name: "depreciationRate", label: "Depreciation rate", type: "number" },
      { name: "nextMaintenanceDate", label: "Next maintenance", type: "date" },
    ],
    actions: [
      { label: "Assign", routeKey: "assets.assign", payload: { assignedTo: "", notes: "Assigned from frontend" } },
      { label: "Return", routeKey: "assets.return" },
      { label: "Maintenance", routeKey: "assets.maintenance", payload: { notes: "Maintenance logged from frontend" } },
      { label: "Dispose", routeKey: "assets.dispose", tone: "danger", payload: { reason: "Disposed from frontend" } },
    ],
  },
  dueMaintenance: {
    title: "Due Maintenance",
    subtitle: "Assets due or overdue for maintenance.",
    routeKey: "assets.dueMaintenance",
    detailPath: "/assets/:id",
    columns: [
      { key: "assetTag", label: "Tag" },
      { key: "itemId.name", label: "Item" },
      { key: "status", label: "Status", status: true },
      { key: "nextMaintenanceDate", label: "Due date" },
    ],
  },
  auditLogs: {
    title: "Audit Logs",
    subtitle: "Review actor, module, entity, and change history across the tenant.",
    routeKey: "auditLogs.list",
    columns: [
      { key: "createdAt", label: "Time" },
      { key: "module", label: "Module" },
      { key: "action", label: "Action" },
      { key: "actorId.name", label: "Actor" },
      { key: "entityType", label: "Entity" },
    ],
  },
  notifications: {
    title: "Notifications",
    subtitle: "Read and manage in-app operational notifications.",
    routeKey: "notifications.list",
    deleteRouteKey: "notifications.delete",
    columns: [
      { key: "title", label: "Title" },
      { key: "message", label: "Message" },
      { key: "type", label: "Type", status: true },
      { key: "readAt", label: "Read" },
      { key: "createdAt", label: "Created" },
    ],
    actions: [
      { label: "Mark read", routeKey: "notifications.markRead" },
    ],
  },
  users: {
    title: "Users",
    subtitle: "Invite and manage tenant users, roles, and assignment scope.",
    routeKey: "users.list",
    createRouteKey: "auth.invite",
    detailRouteKey: "users.getById",
    updateRouteKey: "users.update",
    deleteRouteKey: "users.delete",
    newPath: "/settings/users/new",
    columns: [
      { key: "name", label: "Name" },
      { key: "email", label: "Email" },
      { key: "role", label: "Role", status: true },
      { key: "isActive", label: "Status", status: true },
    ],
    fields: [
      { name: "name", label: "Name", required: true },
      { name: "email", label: "Email", type: "email", required: true },
      { name: "role", label: "Role", type: "select", options: [
        { label: "Admin", value: "admin" },
        { label: "Sub admin", value: "sub_admin" },
        { label: "Store manager", value: "store_manager" },
        { label: "Department head", value: "department_head" },
        { label: "Viewer", value: "viewer" },
      ] },
      { name: "departmentIds", label: "Department IDs JSON", type: "json", helper: "[\"...\"]" },
      { name: "warehouseIds", label: "Warehouse IDs JSON", type: "json", helper: "[\"...\"]" },
    ],
  },
  roles: {
    title: "Roles",
    subtitle: "Create custom roles and permission bundles.",
    routeKey: "roles.list",
    createRouteKey: "roles.create",
    updateRouteKey: "roles.update",
    deleteRouteKey: "roles.delete",
    newPath: "/settings/roles/new",
    columns: [
      { key: "name", label: "Role" },
      { key: "description", label: "Description" },
      { key: "permissions", label: "Permissions" },
      { key: "isActive", label: "Status", status: true },
    ],
    fields: [
      { name: "name", label: "Role name", required: true },
      { name: "description", label: "Description", type: "textarea" },
      { name: "permissions", label: "Permissions JSON", type: "json", helper: "[\"inventory:read\"]" },
    ],
  },
  apiKeys: {
    title: "API Keys",
    subtitle: "Manage scoped API keys for integrations.",
    routeKey: "apiKeys.list",
    createRouteKey: "apiKeys.create",
    deleteRouteKey: "apiKeys.delete",
    newPath: "/settings/api-keys/new",
    columns: [
      { key: "name", label: "Name" },
      { key: "prefix", label: "Prefix" },
      { key: "scopes", label: "Scopes" },
      { key: "status", label: "Status", status: true },
      { key: "lastUsedAt", label: "Last used" },
    ],
    fields: [
      { name: "name", label: "Key name", required: true },
      { name: "scopes", label: "Scopes JSON", type: "json", helper: "[\"inventory:read\"]" },
      { name: "expiresAt", label: "Expires at", type: "date" },
    ],
    actions: [
      { label: "Rotate", routeKey: "apiKeys.rotate" },
      { label: "Revoke", routeKey: "apiKeys.revoke", tone: "danger", payload: { reason: "Revoked from frontend" } },
    ],
  },
  webhooks: {
    title: "Webhooks",
    subtitle: "Manage outbound webhook endpoints, events, and delivery history.",
    routeKey: "webhooks.list",
    createRouteKey: "webhooks.create",
    detailRouteKey: "webhooks.getById",
    updateRouteKey: "webhooks.update",
    deleteRouteKey: "webhooks.delete",
    newPath: "/settings/webhooks/new",
    detailPath: "/settings/webhooks/:id",
    columns: [
      { key: "name", label: "Name" },
      { key: "url", label: "URL" },
      { key: "events", label: "Events" },
      { key: "isActive", label: "Status", status: true },
    ],
    fields: [
      { name: "name", label: "Name", required: true },
      { name: "url", label: "Endpoint URL", required: true },
      { name: "events", label: "Events JSON", type: "json", helper: "[\"stock.low\"]" },
      { name: "secret", label: "Secret" },
      { name: "headers", label: "Headers JSON", type: "json", helper: "{\"x-source\":\"stock-register\"}" },
    ],
    actions: [
      { label: "Test", routeKey: "webhooks.test" },
      { label: "Rotate secret", routeKey: "webhooks.rotateSecret" },
    ],
  },
} satisfies Record<string, ModuleConfig>;

export const relationConfigs = {
  warehouseZones: {
    ...moduleConfigs.warehouses,
    title: "Warehouse Zones",
    subtitle: "Manage bins, aisles, and zones inside this warehouse.",
    routeKey: "warehouses.getZones",
    createRouteKey: "warehouses.createZone",
    columns: [
      { key: "code", label: "Code" },
      { key: "name", label: "Zone" },
      { key: "type", label: "Type" },
      { key: "isActive", label: "Status", status: true },
    ],
    fields: [
      { name: "name", label: "Zone name", required: true },
      { name: "code", label: "Code", required: true },
      { name: "type", label: "Type" },
    ],
    routeParams: (params) => ({ id: params.id ?? "" }),
  },
  warehouseStock: {
    title: "Warehouse Stock",
    subtitle: "Stock balances for the selected warehouse.",
    routeKey: "warehouses.getStock",
    columns: moduleConfigs.stockLevels.columns,
    routeParams: (params) => ({ id: params.id ?? "" }),
  },
  departmentBudget: {
    title: "Department Budget",
    subtitle: "Budget allocation, commitment, and consumption for this department.",
    routeKey: "departments.getBudget",
    columns: [
      { key: "budgetAllocated", label: "Allocated", align: "right" },
      { key: "budgetCommitted", label: "Committed", align: "right" },
      { key: "budgetUsed", label: "Used", align: "right" },
      { key: "availableBudget", label: "Available", align: "right" },
    ],
    routeParams: (params) => ({ id: params.id ?? "" }),
  },
  vendorOrders: {
    title: "Vendor Orders",
    subtitle: "Purchase orders connected to this vendor.",
    routeKey: "vendors.getOrders",
    columns: moduleConfigs.purchaseOrders.columns,
    routeParams: (params) => ({ id: params.id ?? "" }),
  },
  vendorPayments: {
    title: "Vendor Payments",
    subtitle: "Payment history for this vendor.",
    routeKey: "vendors.getPayments",
    columns: moduleConfigs.payments.columns,
    routeParams: (params) => ({ id: params.id ?? "" }),
  },
  assetHistory: {
    title: "Asset History",
    subtitle: "Assignment, return, maintenance, and disposal timeline.",
    routeKey: "assets.history",
    columns: [
      { key: "action", label: "Action", status: true },
      { key: "performedBy.name", label: "Actor" },
      { key: "notes", label: "Notes" },
      { key: "createdAt", label: "Time" },
    ],
    routeParams: (params) => ({ id: params.id ?? "" }),
  },
  webhookDeliveries: {
    title: "Webhook Deliveries",
    subtitle: "Delivery attempts, response codes, and retry state.",
    routeKey: "webhooks.deliveries",
    columns: [
      { key: "event", label: "Event" },
      { key: "status", label: "Status", status: true },
      { key: "attempts", label: "Attempts", align: "right" },
      { key: "responseStatus", label: "HTTP", align: "right" },
      { key: "createdAt", label: "Created" },
    ],
    routeParams: (params) => ({ id: params.id ?? "" }),
  },
} satisfies Record<string, RelationConfig>;

export const reportConfigs = {
  stockSummary: {
    title: "Stock Summary",
    subtitle: "Current stock status grouped by item and warehouse.",
    routeKey: "reports.stockStatus",
    columns: moduleConfigs.stockLevels.columns,
    chart: { xKey: "name", yKey: "availableQuantity" },
  },
  stockMovements: {
    title: "Stock Movements Report",
    subtitle: "Movement volume and value over a date range.",
    routeKey: "reports.stockMovements",
    columns: moduleConfigs.movements.columns,
    chart: { xKey: "date", yKey: "quantity" },
  },
  departmentConsumption: {
    title: "Department Consumption",
    subtitle: "Consumption by department for selected dates.",
    routeKey: "reports.departmentConsumption",
    columns: [
      { key: "departmentName", label: "Department" },
      { key: "quantity", label: "Qty", align: "right" },
      { key: "value", label: "Value", align: "right" },
    ],
    chart: { xKey: "departmentName", yKey: "value" },
  },
  lowStock: {
    title: "Low Stock Report",
    subtitle: "Items below threshold.",
    routeKey: "reports.lowStock",
    columns: moduleConfigs.lowStock.columns,
  },
  deadStock: {
    title: "Dead Stock Report",
    subtitle: "Dead stock uses the item dead-stock endpoint.",
    routeKey: "items.deadStock",
    columns: moduleConfigs.deadStock.columns,
  },
  expiry: {
    title: "Expiry Report",
    subtitle: "Expiry report uses the item expiring endpoint.",
    routeKey: "items.expiring",
    columns: moduleConfigs.expiring.columns,
  },
  valuation: {
    title: "Inventory Valuation",
    subtitle: "Current inventory value by warehouse and item.",
    routeKey: "reports.inventoryValuation",
    columns: [
      { key: "itemName", label: "Item" },
      { key: "warehouseName", label: "Warehouse" },
      { key: "quantity", label: "Qty", align: "right" },
      { key: "totalValue", label: "Value", align: "right" },
    ],
    chart: { xKey: "itemName", yKey: "totalValue" },
  },
  purchaseOrders: {
    title: "Purchase Orders Report",
    subtitle: "Purchase-order status and totals.",
    routeKey: "purchaseOrders.list",
    columns: moduleConfigs.purchaseOrders.columns,
  },
  vendorPerformance: {
    title: "Vendor Performance",
    subtitle: "Vendor comparison and scorecard data.",
    routeKey: "vendors.compare",
    columns: [
      { key: "name", label: "Vendor" },
      { key: "rating", label: "Rating", align: "right" },
      { key: "onTimeRate", label: "On-time", align: "right" },
      { key: "totalOrders", label: "Orders", align: "right" },
    ],
  },
  requestFulfillment: {
    title: "Request Fulfillment",
    subtitle: "Request statuses and fulfillment progress.",
    routeKey: "requests.list",
    columns: moduleConfigs.requests.columns,
  },
  assetUtilization: {
    title: "Asset Utilization",
    subtitle: "Asset status and assignment overview.",
    routeKey: "assets.list",
    columns: moduleConfigs.assets.columns,
  },
  budgetUtilization: {
    title: "Budget Utilization",
    subtitle: "Department budgets and usage.",
    routeKey: "departments.list",
    columns: moduleConfigs.departments.columns,
  },
  auditSummary: {
    title: "Audit Summary",
    subtitle: "Audit log activity summary.",
    routeKey: "auditLogs.list",
    columns: moduleConfigs.auditLogs.columns,
  },
  saved: {
    title: "Saved Reports",
    subtitle: "Saved report configurations and schedules.",
    routeKey: "reports.savedList",
    columns: [
      { key: "name", label: "Name" },
      { key: "kind", label: "Kind" },
      { key: "frequency", label: "Frequency" },
      { key: "nextRunAt", label: "Next run" },
      { key: "isActive", label: "Status", status: true },
    ],
  },
} satisfies Record<string, ReportConfig>;
