import { Role } from "./roles";

export enum Permission {
  ORGANISATION_READ = "organisation:read",
  ORGANISATION_MANAGE = "organisation:manage",
  USER_READ = "user:read",
  USER_MANAGE = "user:manage",
  MASTER_DATA_READ = "master_data:read",
  MASTER_DATA_MANAGE = "master_data:manage",
  INVENTORY_READ = "inventory:read",
  INVENTORY_MANAGE = "inventory:manage",
  STOCK_MOVE = "stock:move",
  REQUEST_CREATE = "request:create",
  REQUEST_READ = "request:read",
  REQUEST_APPROVE = "request:approve",
  REQUEST_FULFILL = "request:fulfill",
  REQUEST_OVERRIDE = "request:override",
  PROCUREMENT_READ = "procurement:read",
  PROCUREMENT_MANAGE = "procurement:manage",
  PO_APPROVE = "purchase_order:approve",
  GRN_CREATE = "grn:create",
  REPORT_READ = "report:read",
  REPORT_EXPORT = "report:export",
  AUDIT_READ = "audit:read",
  NOTIFICATION_READ = "notification:read",
}

const allPermissions = Object.values(Permission);

export const ROLE_PERMISSIONS: Record<Role, readonly Permission[]> = {
  [Role.SUPER_ADMIN]: allPermissions,
  [Role.ADMIN]: allPermissions,
  [Role.SUB_ADMIN]: [
    Permission.ORGANISATION_READ,
    Permission.USER_READ,
    Permission.MASTER_DATA_READ,
    Permission.MASTER_DATA_MANAGE,
    Permission.INVENTORY_READ,
    Permission.INVENTORY_MANAGE,
    Permission.STOCK_MOVE,
    Permission.REQUEST_CREATE,
    Permission.REQUEST_READ,
    Permission.REQUEST_APPROVE,
    Permission.REQUEST_FULFILL,
    Permission.PROCUREMENT_READ,
    Permission.PROCUREMENT_MANAGE,
    Permission.GRN_CREATE,
    Permission.REPORT_READ,
    Permission.REPORT_EXPORT,
    Permission.AUDIT_READ,
    Permission.NOTIFICATION_READ,
  ],
  [Role.STORE_MANAGER]: [
    Permission.MASTER_DATA_READ,
    Permission.INVENTORY_READ,
    Permission.INVENTORY_MANAGE,
    Permission.STOCK_MOVE,
    Permission.REQUEST_READ,
    Permission.REQUEST_FULFILL,
    Permission.PROCUREMENT_READ,
    Permission.GRN_CREATE,
    Permission.REPORT_READ,
    Permission.REPORT_EXPORT,
    Permission.NOTIFICATION_READ,
  ],
  [Role.DEPARTMENT_HEAD]: [
    Permission.MASTER_DATA_READ,
    Permission.INVENTORY_READ,
    Permission.REQUEST_CREATE,
    Permission.REQUEST_READ,
    Permission.REQUEST_APPROVE,
    Permission.REPORT_READ,
    Permission.NOTIFICATION_READ,
  ],
  [Role.VIEWER]: [
    Permission.ORGANISATION_READ,
    Permission.MASTER_DATA_READ,
    Permission.INVENTORY_READ,
    Permission.REQUEST_READ,
    Permission.PROCUREMENT_READ,
    Permission.REPORT_READ,
    Permission.AUDIT_READ,
    Permission.NOTIFICATION_READ,
  ],
};
